### ISSUE TITLE
This type of chart (flow?) would be much more readable

### ISSUE THREAD

**Issue by Ginden** [owenshen24/charting-death#6]
I don't know how it's named, but it's great for showing distributions:

http://2.bp.blogspot.com/-Lz4otdZH25c/T5YOWTm8glI/AAAAAAAADrY/l_0n5LtR7OY/s1600/income-tax-distribution.jpg
https://qph.ec.quoracdn.net/main-qimg-f6571fb249d85da64b6fe26bb9631a61

Though, I don't see an option to create such diagrams in Chart.js.

**Comment by owenshen24** [comment]
[Our World in Data](https://ourworldindata.org/does-the-news-reflect-what-we-die-from) now has this using our data!
